### ISSUE TITLE
When running example9, the kernel crashed.

### ISSUE THREAD

**Issue by ZhongC01** [hongwanliu/darkhistory#5]
![图片](https://user-images.githubusercontent.com/74292783/232325887-956e30f6-f6e0-4a9d-ab62-51a121880b91.png)
There is a jupyter log below. Is there any solution?

**Comment by yitiansun** [comment]
Hi. Can you provide the full jupyter error log (in text)? Also, can you run the `evolve` function with an additional setting `verbose=1` to produce more progress output?

**Comment by ZhongC01** [comment]
> Hi. Can you provide the full jupyter error log (in text)? Also, can you run the `evolve` function with an additional setting `verbose=1` to produce more progress output?

Hi,thank you for your reply. Here are the jupyter error log and the output when verbose=1.

[jupyter log.txt](https://github.com/hongwanliu/DarkHistory/files/11248384/jupyter.log.txt)

![截图 2023-04-17 17-08-57](https://user-images.githubusercontent.com/74292783/232440401-b7d8c060-5797-4660-a665-07131d18b0f8.png)

Thank you very much.

**Comment by yitiansun** [comment]
From the error log it seems to be an issue with the `traitlets` package, and I'm not sure it's related to DarkHistory. I recommend searching for the error message right after the kernel died alert. Also, I noticed that you are using data from "dataverse_files" with v1.1 of DarkHistory. Make sure you turn on the `use_v1_0_data` in `config.py`, or download the v1.1 data files from zenodo (see README).

**Comment by ZhongC01** [comment]
> From the error log it seems to be an issue with the `traitlets` package, and I'm not sure it's related to DarkHistory. I recommend searching for the error message right after the kernel died alert. Also, I noticed that you are using data from "dataverse_files" with v1.1 of DarkHistory. Make sure you turn on the `use_v1_0_data` in `config.py`, or download the v1.1 data files from zenodo (see README).

Thank you for your  recommendation. After multiple attempts, I believe there may be a hardware issue. I ran DarKHistory on a personal computer with 16GB of memory, which may be too small for the data being loaded. Perhaps I need to upgrade my device.(The following is the memory situation when I was running the program. We can see that the memory was suddenly released, and the kernel crashed at that time. Perhaps it was due to occupying too much memory and triggering the memory protection mechanism of ubuntu.)

![截图 2023-04-18 00-06-41](https://user-images.githubusercontent.com/74292783/232771225-ee63b284-c083-4722-b41e-7c2d916a0410.png)

**Comment by yitiansun** [comment]
Thanks for finding out and posting the resolution. For computers with limited memory, one option is to use the NN versions of the transfer function (see release 1.1) which requires less memory (but does requires Tensorflow to be installed).

**Comment by ZhongC01** [comment]
> Thanks for finding out and posting the resolution. For computers with limited memory, one option is to use the NN versions of the transfer function (see release 1.1) which requires less memory (but does requires Tensorflow to be installed).

NN versions of the transfer function do work. Thank you.
